name: PRLabeled
# WARNING!  The run name MUST start with "PR <pr_number>".
# The accompanying privleged workflow parses this to find
# the PR number.  It's the only reliable way it can get it.
run-name: "PR ${{ github.event.number }} Labeled by ${{ github.actor }}"
on:
  pull_request_target:
    types: [ opened,synchronize,labeled ]

jobs:
  TestCalled:
    concurrency:
      group: check-${{ github.base_ref }}-${{ github.ref_name }}
      cancel-in-progress: true
    uses: ./.github/workflows/TestCalledWorkflow.yml
    with:
      jobname:  AAAA
